package com.woniu.pojo;
// Generated 2019-12-18 13:21:22 by Hibernate Tools 5.4.7.Final

/**
 * Dept generated by hbm2java
 */
public class Dept implements java.io.Serializable {

	private Integer deptid;
	private String deptname;
	private String deptloc;

	public Dept() {
	}

	public Dept(String deptname, String deptloc) {
		this.deptname = deptname;
		this.deptloc = deptloc;
	}

	public Integer getDeptid() {
		return this.deptid;
	}

	public void setDeptid(Integer deptid) {
		this.deptid = deptid;
	}

	public String getDeptname() {
		return this.deptname;
	}

	public void setDeptname(String deptname) {
		this.deptname = deptname;
	}

	public String getDeptloc() {
		return this.deptloc;
	}

	public void setDeptloc(String deptloc) {
		this.deptloc = deptloc;
	}

}
